# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roller Painting
email: Charles.Ogilvie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a project to collect recordings of different interpretations of unusual musical scores. Instigated at the start of 2017 around the 'Roller Painting' works of the British artist John Latham as part of an AHRC funded D.Phil at Oxford University by the artist Charles Ogilvie. It was build in collaboration with Ben Doherty, architect of parallel futures and Toby Young, Composer 
baseurl: "/compo" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: charlieogilvie
github_username:  admiralstrand
assetspath: /Assets/

# Build settings
markdown: kramdown


collections:
  - painting1
  - painting2
  - painting3